### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by nery** [eb-rubenespinosa/semver-validation-action#12]
GitHub is now deprecating Node.js 12 and is requiring action maintainers to upgrade to Node.js 16

Full description available in their blog post;
[https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by ostov** [comment]
PR: https://github.com/rubenesp87/semver-validation-action/pull/13

**Comment by tobias-graf-p** [comment]
Hi. I see that this project was already upgraded to node18. When can I expect a new release of the Github action in the marketplace?

**Comment by bkildow** [comment]
@eb-rubenespinosa, can we get a new release for this?

**Comment by rubenesp87** [comment]
@tobias-graf-p @bkildow sorry for the delay 🙏 there is already a new release
